<tsd:PluginWindowBase
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WPFPluginTemplate"
        xmlns:tsd ="clr-namespace:Tekla.Structures.Dialog;assembly=Tekla.Structures.Dialog"
        xmlns:UIControls="clr-namespace:Tekla.Structures.Dialog.UIControls;assembly=Tekla.Structures.Dialog" x:Class="WPFPluginTemplate.MainWindow"
        mc:Ignorable="d"
        Title="{tsd:Loc albl_Title_Plugin}" Height="450" Width="600" FontSize="16">
    <tsd:PluginWindowBase.DataContext>
        <local:MainWindowViewModel></local:MainWindowViewModel>
    </tsd:PluginWindowBase.DataContext>
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="50"/>
            <RowDefinition/>
            <RowDefinition/>
            <RowDefinition Height="50"/>
        </Grid.RowDefinitions>
        <Canvas Grid.Row="1" Width="200" Height="200" HorizontalAlignment="Left" Margin="0,-30,0,0">
            <Rectangle Width="120" Height="120" Margin="40" Stroke="Blue" StrokeThickness="4" RadiusX="5" RadiusY="5"></Rectangle>
            <Ellipse Stroke="Red" Width="30" Height="30" Fill="Red" Margin="50"></Ellipse>
            <Ellipse Stroke="Red" Width="30" Height="30" Fill="Red" Canvas.Left="114" Canvas.Top="50"/>
            <Ellipse Stroke="Red" Width="30" Height="30" Fill="Red" Canvas.Left="50" Canvas.Top="115"/>
            <Ellipse Stroke="Red" Width="30" Height="30" Fill="Red" Canvas.Left="114" Canvas.Top="115"/>
        </Canvas>
        <UIControls:WpfSaveLoad  Width="582" Height="50" HorizontalAlignment="Center" VerticalAlignment="Center" />
        <UIControls:WpfOkApplyModifyGetOnOffCancel HorizontalAlignment="Stretch"  Grid.Row="3" VerticalAlignment="Stretch" ApplyClicked="WpfOkApplyModifyGetOnOffCancel_ApplyClicked" CancelClicked="WpfOkApplyModifyGetOnOffCancel_CancelClicked" GetClicked="WpfOkApplyModifyGetOnOffCancel_GetClicked" ModifyClicked="WpfOkApplyModifyGetOnOffCancel_ModifyClicked" OkClicked="WpfOkApplyModifyGetOnOffCancel_OkClicked" OnOffClicked="WpfOkApplyModifyGetOnOffCancel_OnOffClicked" />
        <Image Source="Image1.png"  Grid.Row="1" Margin="182,10.189,0,10.208" HorizontalAlignment="Left" Stretch="UniformToFill" Width="321"/>

        <Grid Grid.Row="2" >
            <Grid.Resources>
                <Style TargetType="TextBox">
                    <Setter Property="Height" Value="30"></Setter>
                </Style>
                <Style TargetType="Label">
                    <Setter Property="Height" Value="30"></Setter>
                </Style>
                <Style TargetType="UIControls:WpfFilterCheckBox">
                    <Setter Property="Height" Value="30"></Setter>
                    <Setter Property="VerticalContentAlignment" Value="Center"></Setter>
                </Style>
            </Grid.Resources>
            <StackPanel HorizontalAlignment="Left" Margin="10,0,0,0">
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox AttributeName="RebarStep"/>
                    <Label Content="Шаг хомутов" Width="150"></Label>
                    <TextBox Text="{Binding RebarStep}" Width="150"></TextBox>
                </StackPanel>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox AttributeName="RebarSize"/>
                    <Label Content="Ø хомутов" Width="150"></Label>
                    <TextBox Text="{Binding RebarSize}" Width="150"></TextBox>
                </StackPanel>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox  AttributeName="Profile"/>
                    <Label Content="Профиль" Width="150"></Label>
                    <TextBox Text="{Binding Profile}" Width="150"></TextBox>
                </StackPanel>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox  AttributeName="Material"/>
                    <Label Content="Материал" Width="150"></Label>
                    <TextBox Text="{Binding Material}" Width="150"></TextBox>
                    <UIControls:WpfMaterialCatalog x:Name="MaterialCatalog" SelectClicked="MaterialCatalog_SelectClicked" SelectionDone="MaterialCatalog_SelectionDone" VerticalAlignment="Center" HorizontalAlignment="Center"/>
                </StackPanel>
            </StackPanel>

        </Grid>
    </Grid>
</tsd:PluginWindowBase>
